package io;

import superCAD.*;

public class Rhinoscript extends Rhino{

	
//	   void writeTriangle(){
//		    writer.print("x = Array(\t");
//		    writer.print("\t"+toRhinoAsPoint3D(vertices[0])+",");
//		    writer.print("\t"+toRhinoAsPoint3D(vertices[1])+",");
//		    writer.print("\t"+toRhinoAsPoint3D(vertices[2])+",");
//		    writer.print("\t"+toRhinoAsPoint3D(vertices[0])+")");
//		    writer.print("\ny = Rhino.AddPolyline(x)\n");
//		    writer.print("\tIf Not IsNull(y) Then rhino.MeshPolyline(y)\n"); //By Dimitry Demin (Thanks!)
//		    //writer.print("\trhino.MeshPolyline(y)\n");
//		    writer.print("\trhino.DeleteObject(y)\n");
//		    vertexCount = 0;
//		  }

}
